project:
  type: website

website:
  title: "basuarya.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - links.qmd
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

