project:
  type: website
  output-dir: docs
website:
  title: "Spatio-temporal Basu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - news.qmd
      - links.qmd
      - about.qmd 
      

format:
  html:
    theme: readable
    css: styles.css
    toc: true

editor: visual

