---
title: "Home"
format:
  html:
    theme: slate
    code-fold: false
    toc: false
    number-sections: false
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/now" type="text/css"/>
link-citations: true
mainfont: NowRegular
---

Welcome to the homepage of Dr. Aryabrata Basu, an innovative researcher and thought leader at the intersection of virtual reality (VR), human-computer interaction, and artificial intelligence (AI) policy. With a rich background in crafting immersive technologies and a keen eye on the ethical implications of AI, Dr. Basu's work aims to enhance human capabilities and decision-making processes through the thoughtful integration of AI into VR and augmented reality (AR) environments.

As an Assistant Professor in the Department of Computer Science at the University of Arkansas at Little Rock and a research fellow in the Emerging Analytics Center, Dr. Basu is at the forefront of exploring how digital realities can intersect with AI to create more inclusive, effective, and ethically responsible technologies. Whether it's pioneering adaptive learning environments, facilitating human-AI collaboration in critical scenarios, or shaping the future of AI policy, his work is driven by a passion for innovation that serves humanity.

Dr. Basu invites you to explore his latest projects, publications, and collaborative efforts designed to push the boundaries of what's possible in AI and VR, all while prioritizing the human experience at the core of technological advancement. Join him on a journey to redefine the future of immersive technologies and their role in shaping a better world.

Below is an example video-grab of his current research topic into human spatial decision-making! There exists a stark difference between expert and non-expert navigators.

{{< video /images/Non-Immersive_Trajectory.mov width="400" height="240" start="2">}}

::: footer
Copyright © Aryabrata Basu 2024
:::
